HackMe/Controllers/AboutUsController.cs
using HackMe.Application.Enums;
using HackMe.Application.Services;
using Microsoft.AspNetCore.Mvc;

namespace HackMe.Controllers
{
    public class AboutUsController : BaseController
    {
        private readonly ILogger<AboutUsController> _logger;

        public AboutUsController(
            IChallengeTaskService challengeTaskService,
            ILogger<AboutUsController> logger) : base(challengeTaskService)
        {
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            await CreateChallengeResult(ChallengeTaskType.Login);
            return View();
        }
    }
}

HackMe/Controllers/MissionsController.cs
using AutoMapper;
using HackMe.Application.Enums;
using HackMe.Application.Services;
using HackMe.Models;
using Microsoft.AspNetCore.Mvc;

namespace HackMe.Controllers
{
    public class MissionsController : BaseController
    {
        private readonly IAgentService _agentService;
        private readonly IMapper _mapper;

        public MissionsController(
            IAgentService agentService,
            IChallengeTaskService challengeTaskService,
            IMapper mapper) : base(challengeTaskService)
        {
            _agentService = agentService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            var classified = await GetClassifiedSetting(false);
            var results = _agentService.GetMissionsList(string.Empty, classified);

            var viewModel = _mapper.Map<IEnumerable<MissionViewModel>>(results);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Search(string searchKey)
        {
            var classified = await GetClassifiedSetting(false);
            var results = _agentService.GetMissionsList(searchKey, classified);

            var viewModel = _mapper.Map<IEnumerable<MissionViewModel>>(results);
            return View("Index", viewModel);
        }

        public async Task<IActionResult> Detail(string urlKey, bool? showBanner)
        {
            var result = _agentService.GetMissionDetails(GetUserIdentity(), urlKey);

            if (result == null)
            {
                return RedirectToAction("PageNotFound", "Error");
            }

            var classified = await GetClassifiedSetting(result.IsClassified);
            if (result.IsClassified && !classified)
            {
                return RedirectToAction("UnAuthorized", "Error");
            }

            if (showBanner == true)
            {
                SetBanner(true);
            }

            var viewModel = _mapper.Map<MissionViewModel>(result);
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddComment(int id, string comment)
        {
            var identity = GetUserIdentity();            
            var showBanner = await CheckPotentialXSSAndCreateResult(comment);

            var result = _agentService.CreateMissionComment(identity, id, comment);
            if (result == null)
            {
                return RedirectToAction("PageNotFound", "Error");
            }

            return RedirectToAction("Detail", new { result.UrlKey, showBanner });
        }

        private async Task<bool> GetClassifiedSetting(bool createResult)
        {
            var showClassifedDataCookie = HttpContext.Request.Cookies["showClassifiedData"];

            if (bool.TryParse(showClassifedDataCookie, out var showClassifedData) && showClassifedData && createResult)
            {
                await CreateChallengeResult(ChallengeTaskType.ShowClassifiedData);
            }

            return showClassifedData;
        }
    }
}

HackMe/Controllers/ProfileController.cs
using AutoMapper;
using HackMe.Application.Enums;
using HackMe.Application.Services;
using HackMe.Models;
using Microsoft.AspNetCore.Mvc;

namespace HackMe.Controllers
{
    public class ProfileController : BaseController
    {
        private readonly IAgentService _agentService;
        private readonly IMapper _mapper;

        public ProfileController(
            IAgentService agentService,
            IChallengeTaskService challengeTaskService,
            IMapper mapper) : base(challengeTaskService)
        {
            _agentService = agentService;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index(string codeName, bool? showBanner)
        {
            var agent = await _agentService.GetAgent(codeName);

            if (agent == null)
            {
                return RedirectToAction("PageNotFound", "Error");
            }

            var authorized = agent.CodeName == GetUserIdentity();
            if (!authorized)
            {
                var success = await CreateChallengeResult(ChallengeTaskType.UnauthorizedProfile);
                if (success)
                {
                    showBanner = true;
                }
            }

            var viewModel = _mapper.Map<AgentViewModel>(agent);
            viewModel.CanUpdate = authorized;
            SetBanner(showBanner ?? false);
            
            return View(viewModel);
        }

        [HttpPost]
        public async Task<IActionResult> Update(string codeName, string activeMission)
        {
            if (String.IsNullOrEmpty(codeName))
            {
                return RedirectToAction("PageNotFound", "Error");
            }

            var showBanner = false;
            var identity = GetUserIdentity();

            var authorized = codeName == identity;
            if (!authorized)
            {
                showBanner = await CreateChallengeResult(ChallengeTaskType.UpdateOthersProfile);
            }

            await _agentService.UpdateAgentActiveMission(codeName, activeMission);

            var result = await CheckPotentialXSSAndCreateResult(codeName, activeMission);
            showBanner = showBanner ? showBanner : result;

            return RedirectToAction("Index", new { codeName, showBanner });
        }
    }
}

HackMe/Controllers/TasksController.cs
using AutoMapper;
using HackMe.Application.Enums;
using HackMe.Application.Services;
using HackMe.Models;
using Microsoft.AspNetCore.Mvc;

namespace HackMe.Controllers
{
    public class TasksController : BaseController
    {
        private readonly IChallengeTaskService _challengeTaskService;
        private readonly IMapper _mapper;
        private readonly ILogger<TasksController> _logger;

        public TasksController(IChallengeTaskService challengeTaskService,
            IMapper mapper,
            ILogger<TasksController> logger) : base(challengeTaskService)
        {
            _challengeTaskService = challengeTaskService;
            _mapper = mapper;
            _logger = logger;
        }

        public async Task<IActionResult> Index()
        {
            var viewModel = await GetResults();
            return View(viewModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> UpdateMissionsCounter(int counter)
        {            
            if (counter < 0)
            {
                return View("Index", await GetResults());
            }

            var success = await CreateChallengeResult(ChallengeTaskType.CountMissions, counter.ToString());
            var viewModel = await GetResults();

            if (!success && !viewModel.HasCompletedTask(ChallengeTaskType.CountMissions))
            {
                viewModel.ValidationMessage = "Wrong answer! please try again.";
            }

            return View("Index", viewModel);
        }

        private async Task<ChallangeResultsViewModel> GetResults()
        {
            var result = await _challengeTaskService.GetAll(GetUserIdentity());
            return new ChallangeResultsViewModel
            {
                Results = _mapper.Map<IEnumerable<ChallangeResultViewModel>>(result.Results)
            };
        }
    }
}

HackMe/Views/Shared/_Layout.cshtml
@{
    var showHeader = (bool?)ViewBag.ShowHeader ?? true;
    var showBanner = (bool?)ViewBag.showBanner ?? false;
    var userIdentity = User?.Identity?.Name;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Illuminati Agency</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HackMe.styles.css" asp-append-version="true" />
</head>
<body>
    @if (showHeader)
    {
        <header>
            <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
                <div class="container-fluid">
                    <a class="navbar-brand" asp-controller="AboutUs" asp-action="Index">
                        <img src="~/navbar.webp" width="30" height="30" class="d-inline-block align-top" />
                        Illuminati Agency
                    </a>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-controller="AboutUs"
                                   asp-action="Index">About us</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" 
                                    asp-controller="Profile" 
                                    asp-action="Index"
                                   asp-route-codeName="@userIdentity">Profile</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark"
                                   asp-controller="Missions"
                                   asp-action="Index">Missions</a>
                            </li>
                        </ul>
                        <ul class="navbar-nav">
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Tasks" asp-action="Index" title="Challenges">Challenges</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </nav>
        </header>
    }
    
    <div class="container">
        @if (showBanner)
        {
            <div class="alert alert-success" role="alert">
                <p>
                    Congratulations for completing a challenge!
                    <a asp-controller="Tasks" asp-action="Index" title="Tasks" class="alert-link">Check out your progress.</a>
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </p>
            </div>
        }
       
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Illuminati Agency
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>